### ISSUE TITLE
当目录不存在"plugins"文件夹时机器人会崩溃

### ISSUE THREAD

**Issue by Singl-Daemon** [TMBotDev/TMBot#1]
### 该问题是怎么引起的？

没有为"plugins"文件夹作“是否存在’plugins‘文件夹”的判定

### 重现步骤

1: 确保机器人根目录没有plugins文件夹
2: node.exe .\app
3:欣赏崩溃

### 报错信息

19:46:12 ERROR [TMBotMain] 程序出现未捕获的异常:
tools/logger.js:188
19:46:12 ERROR [TMBotMain] Stack: Error: ENOENT: no such file or directory, scandir './plugins/'
    at readdirSync (node:fs:1451:3)
    at PluginPackage.<anonymous> (c:\Users\Administrator\TMBot\TMBot\modules\PluginLoader.js:31:45)
    at Generator.next (<anonymous>)
    at c:\Users\Administrator\TMBot\TMBot\modules\PluginLoader.js:8:71
    at new Promise (<anonymous>)
    at __awaiter (c:\Users\Administrator\TMBot\TMBot\modules\PluginLoader.js:4:12)
    at PluginPackage.LoadAllPackage (c:\Users\Administrator\TMBot\TMBot\modules\PluginLoader.js:30:16)
    at c:\Users\Administrator\TMBot\TMBot\app.js:36:44
    at Generator.next (<anonymous>)
    at c:\Users\Administrator\TMBot\TMBot\app.js:8:71

**Comment by Singl-Daemon** [comment]
Fixed.
